
name: Build Game

on:
  push:
    branches:
      - main
  pull_request:
    branches:
     - main
  workflow_call:
    inputs:
      commit_hash:
        required: false
        description: Optional commit hash to build
        type: string
        default: ${{ github.sha }}

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GODOT_VERSION: 3.5.3

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux, windows, mac]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit_hash }}
          fetch-depth: 0
      - name: export game
        id: export
        # Use latest version (see releases for all versions)
        uses: firebelley/godot-export@v5.2.0
        with:
          # Defining all the required inputs
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.5.3/Godot_v4.0-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.5.3/Godot_v4.0-stable_export_templates.tpz
          relative_project_path: ./
          use_preset_export_path: true
          archive_output: true
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FlappyRace-${{ matrix.platform }}-${{ inputs.commit_hash || github.sha }}
          path: builds/${{ matrix.platform }}
